### ISSUE TITLE
Add capability to create users in Gitea

### ISSUE THREAD

**Issue by ericzolf** [roles-ansible/ansible_role_gitea#155]
Something like the following could be added to the role:

```yaml
- name: Use gitea cli to create user
  ansible.builtin.command: >
    /usr/local/bin/gitea -c {{ gitea_configuration_path }}/gitea.ini admin user create
    --username "{{ item.name }}"
    --password "{{ item.password }}"
    --email "{{ item.email }}"
    --must-change-password=false
  become_user: "{{ gitea_user }}"
  register: gitearesult
  failed_when:
    - '"successfully created" not in gitearesult.stdout'
    - '"user already exists" not in gitearesult.stderr'
  changed_when:
    - '"successfully created" in gitearesult.stdout'
  loop: "{{ gitea_users }}"
```

With `defaults/main.yml` looking like:

```yaml
# list of users to add to Gitea, default is an empty list so that no user is created
gitea_users: []
# example of entry
#  - name: johndoe
#    password: verysecret
#    email: "johndoe@{{ gitea_fqdn }}"
```
