### ISSUE TITLE
Invalid default values for gitea_actions_default_actions_url

### ISSUE THREAD

**Issue by NicoFgrx** [roles-ansible/ansible_role_gitea#158]
Hi !

First of all, thanks for create and maintain this ansible role ! That's very usefull :) 

I'm currently trying to automate my homelab gitea instance with Actions activate and use local mirror of actions repos.
I'm using this playbook :
```
- name: "Install gitea"
  hosts:  "{{ target }}"
  roles:
    - {role: l3d.gitea, tags: gitea}
  vars:
    ...
    gitea_actions_enabled: true # activate actions
    gitea_require_signin: false # use by actions to git clone actions/<repo>
    ...
```
But I have this message : `2024/04/01 11:14:55 ...s/setting/actions.go:64:loadActionsFrom() [E] [actions] DEFAULT_ACTIONS_URL does not support "https://gitea.com" as custom URL any longer, fallback to "github"`

By default, `gitea_actions_default_actions_url` will be replace by `https://gitea.com` but it's no longer supported by gitea see [this PR](https://github.com/go-gitea/gitea/pull/25604)
Only "github" or "self" are valid inputs.
