### ISSUE TITLE
BUG: `gitea_theme_default` variable in host_vars get overwritten by default variable

### ISSUE THREAD

**Issue by apesoda** [roles-ansible/ansible_role_gitea#198]
If {{ gitea_theme_default }} is set under a host_var the task "Configure gitea" will use the 
{{ gitea_theme_default }} of the chosen fork .yml from the defaults/ folder anyways.

```
TASK [roles-ansible.gitea : Configure gitea] **************************************************
--- before: /etc/gitea/gitea.ini
+++ after: /home/ansible/.ansible/tmp/ansible-local-354369cycuboxu/tmptrrlwnv4/gitea.ini.j2
@@ -33,7 +33,7 @@
 ; -> https://docs.gitea.com/next/administration/config-cheat-sheet/#ui-ui
 [ui]
 THEMES = forgejo-auto,forgejo-light,forgejo-dark,gitea-auto,gitea-light,gitea-dark,forgejo-auto-deuteranopia-protanopia,forgejo-light-deuteranopia-protanopia,forgejo-dark-deuteranopia-protanopia,forgejo-auto-tritanopia,forgejo-light-tritanopia,forgejo-dark-tritanopia
-DEFAULT_THEME = gitea-auto
+DEFAULT_THEME = forgejo-auto
 SHOW_USER_EMAIL = false
```

My guess is that the cause lies here:

from tasks/main.yml
```
- name: Gather Gitea/Forgejo UI Theme variables
  ansible.builtin.include_vars:
    file: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ gitea_fork }}.yml"
      paths:
        - "defaults"
```

Since include_vars has precedence over host_vars (as per: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html) the value you assign to this variable in the host_var will never be chosen.
