### ISSUE TITLE
importing gpg key fails

### ISSUE THREAD

**Issue by thigg** [roles-ansible/ansible_role_gitea#29]
When installing, the import of the gpg key seems to fail, even if its set as argument:

`fatal: [default]: FAILED! => {"changed": false, "cmd": ["gpg", "--verify", "/tmp/gitea-1.14.1.linux-amd64.xz.asc", "/tmp/gitea-1.14.1.linux-amd64.xz"], "delta": "0:00:00.390815", "end": "2021-04-19 16:04:15.835407", "msg": "non-zero return code", "rc": 2, "start": "2021-04-19 16:04:15.444592", "stderr": "gpg: Signature made Fri 16 Apr 2021 03:21:09 AM UTC using RSA key ID 9753F4B0\ngpg: Can't check signature: No public key", "stderr_lines": ["gpg: Signature made Fri 16 Apr 2021 03:21:09 AM UTC using RSA key ID 9753F4B0", "gpg: Can't check signature: No public key"], "stdout": "", "stdout_lines": []}`

The used playbook:

```
---
# ansible-galaxy install do1jlr.gitea
- name: "Install gitea"
  hosts: all
  roles:
    - {role: do1jlr.gitea, tags: gitea}
  vars:
    # Here we assume we are behind a reverse proxy that will
    # handle https for us, so we bind on localhost:3000 using HTTP
    gitea_http_domain: 'localhost'
    gitea_root_url: 'http://localhost'
    gitea_protocol: http
    gitea_gpg_key: 7C9E68152594688862D62AF62D9AE806EC1592E2

    gitea_ssh_domain: localhost
    gitea_start_ssh: true
    gitea_http_listen: 0.0.0.0
```

Tried this with the following vagrant box:

```
Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian10"
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y python-apt
   SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
   config.vm.network "forwarded_port", guest: 3000, host: 8083
end
```
